#!/bin/bash
set -euo pipefail

# Naton Shopper - automatic setup for 3 VPS / 2 configs each
# 6 world lists, distributed sequentially across the 3 VPS.
# VPS 1: uey1
# VPS 2: w8x8
# VPS 3: w8x6

NATON_DIR="/root/.onlybot/naton-scripts/Naton Shopper/settings"
HOST="$(hostname -s 2>/dev/null || hostname)"

# ---------- World lists (218 worlds / 6 lists) ----------
WORLDS_1="302,303,304,305,306,307,309,310,311,312,313,314,315,317,320,321,322,323,324,325,327,328,329,330,331,332,333,334,336,337,338,339,340,341,342,343,344"
WORLDS_2="346,347,348,350,351,352,354,355,356,357,358,359,360,362,365,367,368,369,370,371,374,375,376,377,378,385,386,387,388,389,390,394,395,402,403,404,405"
WORLDS_3="406,407,408,409,410,411,412,421,422,424,425,426,438,439,440,441,442,443,444,445,446,457,458,459,461,462,463,464,465,466,470,471,472,473,474,475"
WORLDS_4="476,477,478,479,480,481,482,484,485,486,487,488,489,490,491,492,493,494,495,496,500,501,503,504,505,506,507,508,509,510,511,512,513,514,515,516"
WORLDS_5="517,518,519,520,521,522,523,524,525,531,532,533,534,535,536,538,541,542,543,544,545,546,547,550,551,556,557,559,562,563,564,566,567,569,573,574"
WORLDS_6="575,582,590,591,596,597,599,600,601,602,603,604,609,610,611,612,613,614,615,619,620,621,622,624,625,626,661,662,663,664,668,693,694,695,699,700"

# ---------- Select lists from hostname ----------
case "$HOST" in
    uey1)
        VPS_NAME="VPS 1"
        WORLDS_1="${WORLDS_1}"
        WORLDS_2="${WORLDS_2}"
        ;;
    w8x8)
        VPS_NAME="VPS 2"
        WORLDS_1="${WORLDS_3}"
        WORLDS_2="${WORLDS_4}"
        ;;
    w8x6)
        VPS_NAME="VPS 3"
        WORLDS_1="${WORLDS_5}"
        WORLDS_2="${WORLDS_6}"
        ;;
    *)
        echo "ERROR: Unknown hostname: $HOST"
        echo "Allowed: uey1 w8x8 w8x6"
        exit 1
        ;;
esac

mkdir -p "$NATON_DIR"

create_config() {
    local file="$1"
    local worlds="$2"
    if [[ -f "$file" ]]; then
        cp -a "$file" "${file}.backup.$(date +%Y%m%d-%H%M%S)"
        echo "Backup created for $file"
    fi
    cat > "$file" <<EOF
#Naton Shopper Settings
#Generated by 3-VPS / 6-world-list setup
AcceptAidConfig={"configureAcceptAid"\:false,"disableAcceptAid"\:false}
AutoBondConfig={"dontSellItemsForGold"\:false,"obtainGoldFromMuleIfOut"\:false,"use"\:true,"rebondDays"\:2,"price"\:{"percentToAdd"\:0.0,"gpToAdd"\:0,"runelite"\:false,"useStaticPrice"\:false,"relistPolicy"\:{"range"\:{"min"\:5,"max"\:10,"type"\:"UNIFORM","upperPlayerRandomization"\:20.0,"lowerPlayerRandomization"\:-20.0},"nextPrice"\:{"percentToAdd"\:0.0,"gpToAdd"\:0,"runelite"\:false,"useStaticPrice"\:false,"relistPolicy"\:{"range"\:{"min"\:5,"max"\:10,"type"\:"UNIFORM","upperPlayerRandomization"\:20.0,"lowerPlayerRandomization"\:-20.0},"nextPrice"\:{"percentToAdd"\:0.0,"gpToAdd"\:0,"runelite"\:false,"useStaticPrice"\:false,"useArrowkeyPrice"\:true,"staticPrice"\:0,"arrowKeyAdjustment"\:4,"runelitePriceType"\:"AVERAGE","osbuddy"\:false},"timeUnit"\:"MINUTES"},"useArrowkeyPrice"\:true,"staticPrice"\:0,"arrowKeyAdjustment"\:3,"runelitePriceType"\:"AVERAGE","osbuddy"\:false},"timeUnit"\:"MINUTES"},"useArrowkeyPrice"\:true,"staticPrice"\:0,"arrowKeyAdjustment"\:2,"runelitePriceType"\:"AVERAGE","osbuddy"\:false},"cancelPendingBuyOffersForGold"\:false}
BankScrollConfig={"scrollMethod"\:"DEFAULT"}
CameraAngleConfig={"cameraAngleMin"\:70,"cameraAngleMax"\:100,"keepCameraAngleInRange"\:false}
CameraRotationConfig={"keepCameraRotationInRange"\:false,"cameraRotationMin"\:360,"cameraRotationMax"\:100}
CameraZoomConfig={"zoom"\:{"min"\:50,"max"\:80,"sd"\:8,"avg"\:70,"type"\:"NORMAL"},"frequencyTimeUnit"\:"MINUTES","frequency"\:{"min"\:15,"max"\:40,"type"\:"UNIFORM"},"enabled"\:false}
ChatHandlerConfig={"loopSleep"\:{"min"\:100,"max"\:125,"type"\:"UNIFORM","upperPlayerRandomization"\:20.0,"lowerPlayerRandomization"\:-20.0},"keyOptions"\:true,"beforeContinue"\:{"min"\:100,"max"\:5000,"sd"\:182,"avg"\:420,"type"\:"NORMAL","upperPlayerRandomization"\:20.0,"lowerPlayerRandomization"\:-20.0},"keyContinue"\:true,"beforeOption"\:{"min"\:180,"max"\:5000,"sd"\:192,"avg"\:550,"type"\:"NORMAL","upperPlayerRandomization"\:20.0,"lowerPlayerRandomization"\:-20.0},"holdSpace"\:false}
ChatModeConfig={"gameChatMode"\:"ALL","channelChatMode"\:"ON","configurePrivateChat"\:false,"configureTradeChat"\:false,"configureChannelChat"\:false,"publicChatMode"\:"ON","configureClanChat"\:false,"privateChatMode"\:"ALL","tradeChatMode"\:"ON","configurePublicChat"\:false,"configureGameChat"\:false,"clanChatMode"\:"ON"}
DaxWalkerConfig={"enableTeleporting"\:true,"enableSeed"\:false,"useDentistWalker"\:false}
DiscordWebhookConfig={"sendOnDeath"\:false,"sendOnFrequencyMinutes"\:60,"useWebooks"\:false,"sendOnInaccessible"\:false,"sendOnStart"\:false,"sendOnPet"\:false,"sendOnEnd"\:false,"itemGainedWatchList"\:"","webhookUrl"\:"","sendOnItemGained"\:false,"sendOnAntiPk"\:false,"sendOnFrequency"\:false,"itemGainedMinValue"\:0,"sendOnLevel"\:false}
DiscordWebhookOnAntiPkMessageConfig={"customMessage"\:"Anti-PK triggered in world ${world} at ${position}\!","includeImage"\:true}
DiscordWebhookOnDeathMessageConfig={"customMessage"\:"${username} has died\!","includeImage"\:true}
DiscordWebhookOnEndMessageConfig={"customMessage"\:"Script Ending ${script-name}\\nRuntime\: ${script-runtime}\\nStop Reason\: ${stop-reason}","includeImage"\:true}
DiscordWebhookOnFrequencyMessageConfig={"customMessage"\:"Script Running ${script-name}\\nRuntime\: ${script-runtime}","includeImage"\:true}
DiscordWebhookOnInaccessibleMessageConfig={"customMessage"\:"Account Inaccessible\: ${username} is ${inaccessible-type}","includeImage"\:true}
DiscordWebhookOnItemGainedMessageConfig={"customMessage"\:"${username} received ${gained-item-quantity} x ${gained-item-name} (worth ${gained-item-value} gp)\!","includeImage"\:true}
DiscordWebhookOnLevelMessageConfig={"customMessage"\:"${username} has leveled ${gained-skill-type} to ${gained-skill-level}","includeImage"\:true}
DiscordWebhookOnPetMessageConfig={"customMessage"\:"Pet alert for ${username}\! ${pet-message}","includeImage"\:true}
DiscordWebhookOnStartMessageConfig={"customMessage"\:"Script Starting ${script-name}","includeImage"\:true}
DynamicAntibanConfig={"alwaysHover"\:false,"timedActions"\:["CHECK_EXP","RANDOM_RIGHT_CLICK","MOVE_MOUSE","ROTATE_CAMERA","PICK_UP_MOUSE","MOUSE_LEAVE_GAME","EXAMINE_ENTITY","CHECK_TABS"],"reactionTimeScale"\:20.0,"useReactionTimes"\:false}
DynamicClientStateConfig={"openOnEnd"\:false,"hideOnStart"\:false}
DynamicControlsConfig={"customMouseSpeed"\:false,"mouseSpeedMax"\:100,"cameraType"\:"CLIENT_CAMERA_ANTIBAN","mouseSpeedMin"\:100}
DynamicOptionalFailsafeConfig={"removeRoofs"\:false,"adjustCameraZoom"\:false}
DynamicPrefZoomConfig={"maxPrefZoom"\:50,"usePrefZoom"\:false,"minPrefZoom"\:50}
DynamicSoundMuteConfig={"disableSoundsLoginScreen"\:false,"disableSoundsInGame"\:false}
DynamicStuckFailsafeConfig={"enabled"\:true}
DynamicTimeBasedHoppingConfig={"average"\:0,"timeBasedHopping"\:false,"min"\:0,"sd"\:0,"max"\:0}
DynamicWorldHopPlayersConfig={"hopPlayerTalks"\:false,"onlyHopAtWorkArea"\:true,"hopPlayersInRange"\:false,"maxPlayersInRange"\:0,"playerSearchRange"\:0}
DynamicWorldListConfig={"worlds"\:[$worlds],"excludeListedWorlds"\:false,"hopSequential"\:false,"hopRandom"\:true,"minSecondsPerWorld"\:0}
FkeyConfig={"useFkeys"\:false,"overrideFkeySetting"\:false}
LogoutOnEndConfig={"logoutOnEnd"\:false}
LogoutThumbsUpConfig={"xHoursSince"\:6,"enableClickingThumbsOnLogout"\:false,"onlyClickIfXHoursSince"\:false,"thumbsUpChance"\:50,"thumbsDownChance"\:50}
LoopSleepConfig={"loopSleepRange"\:{"min"\:45,"max"\:65,"type"\:"UNIFORM","upperPlayerRandomization"\:20.0,"lowerPlayerRandomization"\:-20.0},"overrideLoopSleep"\:false}
MaxExchangeActionLengthConfig={"range"\:{"min"\:60,"max"\:90,"type"\:"UNIFORM","upperPlayerRandomization"\:20.0,"lowerPlayerRandomization"\:-20.0},"timeUnit"\:"MINUTES"}
ResizableConfig={"configureResizable"\:false,"resizableType"\:"RESIZABLE_MODERN"}
ScreenshotOnEndConfig={"screenshot"\:false,"onlyAfterXMinutes"\:false,"xMinutes"\:60}
SleepModifierConfig={"modifier"\:{"min"\:95,"max"\:105,"type"\:"UNIFORM"},"enable"\:false}
buyBatch=BATCHES_OF_5
cashIn=false
cashInAmount=0
customBuyPrices={"66"\:{"percentToAdd"\:0.0,"gpToAdd"\:0,"runelite"\:false,"useStaticPrice"\:true,"useArrowkeyPrice"\:false,"staticPrice"\:270,"arrowKeyAdjustment"\:0,"runelitePriceType"\:"AVERAGE","osbuddy"\:false},"21326"\:{"percentToAdd"\:0.0,"gpToAdd"\:0,"runelite"\:false,"useStaticPrice"\:true,"useArrowkeyPrice"\:false,"staticPrice"\:210,"arrowKeyAdjustment"\:0,"runelitePriceType"\:"AVERAGE","osbuddy"\:false},"30800"\:{"percentToAdd"\:0.0,"gpToAdd"\:0,"runelite"\:false,"useStaticPrice"\:true,"useArrowkeyPrice"\:false,"staticPrice"\:250,"arrowKeyAdjustment"\:0,"runelitePriceType"\:"AVERAGE","osbuddy"\:false},"855"\:{"percentToAdd"\:0.0,"gpToAdd"\:0,"runelite"\:false,"useStaticPrice"\:true,"useArrowkeyPrice"\:false,"staticPrice"\:600,"arrowKeyAdjustment"\:0,"runelitePriceType"\:"AVERAGE","osbuddy"\:false},"859"\:{"percentToAdd"\:0.0,"gpToAdd"\:0,"runelite"\:false,"useStaticPrice"\:true,"useArrowkeyPrice"\:false,"staticPrice"\:1275,"arrowKeyAdjustment"\:0,"runelitePriceType"\:"AVERAGE","osbuddy"\:false},"9244"\:{"percentToAdd"\:0.0,"gpToAdd"\:0,"runelite"\:false,"useStaticPrice"\:true,"useArrowkeyPrice"\:false,"staticPrice"\:460,"arrowKeyAdjustment"\:0,"runelitePriceType"\:"AVERAGE","osbuddy"\:false},"31004"\:{"percentToAdd"\:0.0,"gpToAdd"\:0,"runelite"\:false,"useStaticPrice"\:true,"useArrowkeyPrice"\:false,"staticPrice"\:80,"arrowKeyAdjustment"\:0,"runelitePriceType"\:"AVERAGE","osbuddy"\:false},"31010"\:{"percentToAdd"\:0.0,"gpToAdd"\:0,"runelite"\:false,"useStaticPrice"\:true,"useArrowkeyPrice"\:false,"staticPrice"\:100,"arrowKeyAdjustment"\:0,"runelitePriceType"\:"AVERAGE","osbuddy"\:false},"1635"\:{"percentToAdd"\:0.0,"gpToAdd"\:0,"runelite"\:false,"useStaticPrice"\:true,"useArrowkeyPrice"\:false,"staticPrice"\:190,"arrowKeyAdjustment"\:0,"runelitePriceType"\:"AVERAGE","osbuddy"\:false},"31973"\:{"percentToAdd"\:0.0,"gpToAdd"\:0,"runelite"\:false,"useStaticPrice"\:true,"useArrowkeyPrice"\:false,"staticPrice"\:1275,"arrowKeyAdjustment"\:0,"runelitePriceType"\:"AVERAGE","osbuddy"\:false},"21352"\:{"percentToAdd"\:0.0,"gpToAdd"\:0,"runelite"\:false,"useStaticPrice"\:true,"useArrowkeyPrice"\:false,"staticPrice"\:800,"arrowKeyAdjustment"\:0,"runelitePriceType"\:"AVERAGE","osbuddy"\:false},"1517"\:{"percentToAdd"\:0.0,"gpToAdd"\:0,"runelite"\:false,"useStaticPrice"\:true,"useArrowkeyPrice"\:false,"staticPrice"\:25,"arrowKeyAdjustment"\:0,"runelitePriceType"\:"AVERAGE","osbuddy"\:false},"2357"\:{"percentToAdd"\:0.0,"gpToAdd"\:0,"runelite"\:false,"useStaticPrice"\:true,"useArrowkeyPrice"\:false,"staticPrice"\:115,"arrowKeyAdjustment"\:0,"runelitePriceType"\:"AVERAGE","osbuddy"\:false},"1654"\:{"percentToAdd"\:0.0,"gpToAdd"\:0,"runelite"\:false,"useStaticPrice"\:true,"useArrowkeyPrice"\:false,"staticPrice"\:190,"arrowKeyAdjustment"\:0,"runelitePriceType"\:"AVERAGE","osbuddy"\:false},"9144"\:{"percentToAdd"\:0.0,"gpToAdd"\:0,"runelite"\:false,"useStaticPrice"\:true,"useArrowkeyPrice"\:false,"staticPrice"\:130,"arrowKeyAdjustment"\:0,"runelitePriceType"\:"AVERAGE","osbuddy"\:false},"1656"\:{"percentToAdd"\:0.0,"gpToAdd"\:0,"runelite"\:false,"useStaticPrice"\:true,"useArrowkeyPrice"\:false,"staticPrice"\:570,"arrowKeyAdjustment"\:0,"runelitePriceType"\:"AVERAGE","osbuddy"\:false},"1658"\:{"percentToAdd"\:0.0,"gpToAdd"\:0,"runelite"\:false,"useStaticPrice"\:true,"useArrowkeyPrice"\:false,"staticPrice"\:730,"arrowKeyAdjustment"\:0,"runelitePriceType"\:"AVERAGE","osbuddy"\:false},"19580"\:{"percentToAdd"\:0.0,"gpToAdd"\:0,"runelite"\:false,"useStaticPrice"\:true,"useArrowkeyPrice"\:false,"staticPrice"\:550,"arrowKeyAdjustment"\:0,"runelitePriceType"\:"AVERAGE","osbuddy"\:false},"892"\:{"percentToAdd"\:0.0,"gpToAdd"\:0,"runelite"\:false,"useStaticPrice"\:true,"useArrowkeyPrice"\:false,"staticPrice"\:195,"arrowKeyAdjustment"\:0,"runelitePriceType"\:"AVERAGE","osbuddy"\:false},"1660"\:{"percentToAdd"\:0.0,"gpToAdd"\:0,"runelite"\:false,"useStaticPrice"\:true,"useArrowkeyPrice"\:false,"staticPrice"\:1270,"arrowKeyAdjustment"\:0,"runelitePriceType"\:"AVERAGE","osbuddy"\:false},"19582"\:{"percentToAdd"\:0.0,"gpToAdd"\:0,"runelite"\:false,"useStaticPrice"\:true,"useArrowkeyPrice"\:false,"staticPrice"\:1000,"arrowKeyAdjustment"\:0,"runelitePriceType"\:"AVERAGE","osbuddy"\:false},"830"\:{"percentToAdd"\:0.0,"gpToAdd"\:0,"runelite"\:false,"useStaticPrice"\:true,"useArrowkeyPrice"\:false,"staticPrice"\:195,"arrowKeyAdjustment"\:0,"runelitePriceType"\:"AVERAGE","osbuddy"\:false},"4542"\:{"percentToAdd"\:0.0,"gpToAdd"\:0,"runelite"\:false,"useStaticPrice"\:true,"useArrowkeyPrice"\:false,"staticPrice"\:25,"arrowKeyAdjustment"\:0,"runelitePriceType"\:"AVERAGE","osbuddy"\:false},"62"\:{"percentToAdd"\:0.0,"gpToAdd"\:0,"runelite"\:false,"useStaticPrice"\:true,"useArrowkeyPrice"\:false,"staticPrice"\:130,"arrowKeyAdjustment"\:0,"runelitePriceType"\:"AVERAGE","osbuddy"\:false},"28991"\:{"percentToAdd"\:0.0,"gpToAdd"\:0,"runelite"\:false,"useStaticPrice"\:true,"useArrowkeyPrice"\:false,"staticPrice"\:195,"arrowKeyAdjustment"\:0,"runelitePriceType"\:"AVERAGE","osbuddy"\:false}}
customSellPrices={}
defaultBuyPrice={"percentToAdd"\:0.0,"gpToAdd"\:0,"runelite"\:false,"useStaticPrice"\:false,"useArrowkeyPrice"\:true,"staticPrice"\:0,"arrowKeyAdjustment"\:2,"runelitePriceType"\:"AVERAGE","osbuddy"\:false}
defaultSellPrice={"percentToAdd"\:0.0,"gpToAdd"\:0,"runelite"\:false,"useStaticPrice"\:false,"useArrowkeyPrice"\:true,"staticPrice"\:0,"arrowKeyAdjustment"\:-2,"runelitePriceType"\:"AVERAGE","osbuddy"\:false}
enableGERestocking=true
equipBankTeleport=false
equipShopTeleport=false
fastOpenPacks=false
hopWhenEmpty=true
items=[{"itemId"\:19580,"transactionType"\:"SELL","shopStockLimit"\:10,"quantity"\:10000},{"itemId"\:21352,"transactionType"\:"SELL","shopStockLimit"\:10,"quantity"\:10000},{"itemId"\:19582,"transactionType"\:"SELL","shopStockLimit"\:10,"quantity"\:10000},{"itemId"\:9244,"transactionType"\:"SELL","shopStockLimit"\:10,"quantity"\:10000},{"itemId"\:892,"transactionType"\:"SELL","shopStockLimit"\:10,"quantity"\:10000},{"itemId"\:28991,"transactionType"\:"SELL","shopStockLimit"\:10,"quantity"\:10000},{"itemId"\:9144,"transactionType"\:"SELL","shopStockLimit"\:10,"quantity"\:10000},{"itemId"\:31004,"transactionType"\:"SELL","shopStockLimit"\:10,"quantity"\:10000},{"itemId"\:31010,"transactionType"\:"SELL","shopStockLimit"\:10,"quantity"\:10000},{"itemId"\:21326,"transactionType"\:"SELL","shopStockLimit"\:10,"quantity"\:10000},{"itemId"\:830,"transactionType"\:"SELL","shopStockLimit"\:10,"quantity"\:10000},{"itemId"\:855,"transactionType"\:"SELL","shopStockLimit"\:10,"quantity"\:10000},{"itemId"\:4542,"transactionType"\:"SELL","shopStockLimit"\:10,"quantity"\:10000},{"itemId"\:1517,"transactionType"\:"SELL","shopStockLimit"\:10,"quantity"\:10000},{"itemId"\:859,"transactionType"\:"SELL","shopStockLimit"\:10,"quantity"\:10000},{"itemId"\:30800,"transactionType"\:"SELL","shopStockLimit"\:10,"quantity"\:10000},{"itemId"\:1654,"transactionType"\:"SELL","shopStockLimit"\:10,"quantity"\:10000},{"itemId"\:1635,"transactionType"\:"SELL","shopStockLimit"\:10,"quantity"\:10000},{"itemId"\:66,"transactionType"\:"SELL","shopStockLimit"\:10,"quantity"\:10000},{"itemId"\:2357,"transactionType"\:"SELL","shopStockLimit"\:10,"quantity"\:10000},{"itemId"\:62,"transactionType"\:"SELL","shopStockLimit"\:10,"quantity"\:10000},{"itemId"\:31973,"transactionType"\:"SELL","shopStockLimit"\:6,"quantity"\:6000},{"itemId"\:1658,"transactionType"\:"SELL","shopStockLimit"\:3,"quantity"\:3000},{"itemId"\:1656,"transactionType"\:"SELL","shopStockLimit"\:3,"quantity"\:3000},{"itemId"\:1660,"transactionType"\:"SELL","shopStockLimit"\:3,"quantity"\:3000}]
mule=false
muleAddress=127.0.0.1
muleForCoinsOnRestock=false
muleGPToKeep=500000
muleGoldTargetOnRestock=0
muleID=1
muleIfOver=1000000
muleThreshold=false
muleTripOnThreshold=true
napiMiniBreak={"breakLengthRange"\:{"min"\:171,"max"\:289,"sd"\:48,"avg"\:194,"type"\:"NORMAL","upperPlayerRandomization"\:20.0,"lowerPlayerRandomization"\:-20.0},"breakFrequencyRange"\:{"min"\:221,"max"\:2068,"sd"\:392,"avg"\:1961,"type"\:"NORMAL","upperPlayerRandomization"\:20.0,"lowerPlayerRandomization"\:-20.0},"miniBreaking"\:false}
napiRandomAfk={"frequencyRange"\:{"min"\:662,"max"\:2900,"sd"\:409,"avg"\:2046,"type"\:"NORMAL","upperPlayerRandomization"\:20.0,"lowerPlayerRandomization"\:-20.0},"afkLengthRange"\:{"min"\:56,"max"\:371,"sd"\:35,"avg"\:142,"type"\:"NORMAL","upperPlayerRandomization"\:20.0,"lowerPlayerRandomization"\:-20.0},"mouseOffScreenChance"\:"ALWAYS","randomAfking"\:false}
progressionEntries=[]
repeatProgression=false
repeatWhenDone=false
restockOnStart=true
selectedShopTile={"x"\:2099,"y"\:3906,"z"\:0}
settingsVersion=0
shopNpcName=Melana Moonlander
stopConditionExp={"allMatch"\:false,"conditions"\:[]}
useProgressiveMode=false
EOF
    chmod 644 "$file"
}

create_config "$NATON_DIR/1.ini" "$WORLDS_1"
create_config "$NATON_DIR/2.ini" "$WORLDS_2"

echo "=========================================="
echo " Naton setup completed"
echo " Host: $HOST"
echo " VPS:  $VPS_NAME"
echo "=========================================="
echo "1.ini:"
grep '^DynamicWorldListConfig=' "$NATON_DIR/1.ini"
echo "2.ini:"
grep '^DynamicWorldListConfig=' "$NATON_DIR/2.ini"
echo "Files:"
ls -lh "$NATON_DIR/1.ini" "$NATON_DIR/2.ini"
