#!/bin/bash
set -euo pipefail

# ============================================================
# Naton Shopper - automatic setup for 9 VPS / 2 configs each
#
# IMPORTANT:
# - VPS 1-4 hostnames are the original hostnames.
# - VPS 5-9 are ready; enter their hostnames in the section below.
# - Worlds use the NEW world list and are split in consecutive order.
# - The script creates 1.ini and 2.ini on every VPS.
# ============================================================

# ---------- VPS HOSTNAMES ----------
# The first 4 hostnames are the existing VPS and are kept unchanged.
# When the 5 new VPS are ready, only fill HOST_VPS5 ... HOST_VPS9.
HOST_VPS1="sgur.c.dedikuoti.lt"
HOST_VPS2="rvsa.c.dedikuoti.lt"
HOST_VPS3="t39e.c.dedikuoti.lt"
HOST_VPS4="t4a4.c.dedikuoti.lt"

HOST_VPS5=""
HOST_VPS6=""
HOST_VPS7=""
HOST_VPS8=""
HOST_VPS9=""

NATON_DIR="/root/.onlybot/naton-scripts/Naton Shopper/settings"
HOST="$(hostname -f 2>/dev/null || hostname)"

# ---------- World lists ----------
WORLD_1='302,303,304,305,306,307,309,310,311,312,313,314,315'
WORLD_2='317,320,321,322,323,324,325,327,328,329,330,331,332'
WORLD_3='333,334,336,337,338,339,340,341,342,343,344,346'
WORLD_4='347,348,350,351,352,354,355,356,357,358,359,360'
WORLD_5='362,365,367,368,369,370,371,374,375,376,377,378'
WORLD_6='385,386,387,388,389,390,394,395,402,403,404,405'
WORLD_7='406,407,408,409,410,411,412,421,422,424,425,426'
WORLD_8='438,439,440,441,442,443,444,445,446,457,458,459'
WORLD_9='461,462,463,464,465,466,470,471,472,473,474,475'
WORLD_10='476,477,478,479,480,481,482,484,485,486,487,488'
WORLD_11='489,490,491,492,493,494,495,496,500,501,503,504'
WORLD_12='505,506,507,508,509,510,511,512,513,514,515,516'
WORLD_13='517,518,519,520,521,522,523,524,525,531,532,533'
WORLD_14='534,535,536,538,541,542,543,544,545,546,547,550'
WORLD_15='551,556,557,559,562,563,564,566,567,569,573,574'
WORLD_16='575,582,590,591,596,597,599,600,601,602,603,604'
WORLD_17='609,610,611,612,613,614,615,619,620,621,622,624'
WORLD_18='625,626,661,662,663,664,668,693,694,695,699,700'

# ---------- Select lists from hostname ----------
case "$HOST" in
    "$HOST_VPS1")
        VPS_NAME="VPS 1"
        WORLDS_1="$WORLD_1"
        WORLDS_2="$WORLD_2"
        ;;
    "$HOST_VPS2")
        VPS_NAME="VPS 2"
        WORLDS_1="$WORLD_3"
        WORLDS_2="$WORLD_4"
        ;;
    "$HOST_VPS3")
        VPS_NAME="VPS 3"
        WORLDS_1="$WORLD_5"
        WORLDS_2="$WORLD_6"
        ;;
    "$HOST_VPS4")
        VPS_NAME="VPS 4"
        WORLDS_1="$WORLD_7"
        WORLDS_2="$WORLD_8"
        ;;
    "$HOST_VPS5")
        VPS_NAME="VPS 5"
        WORLDS_1="$WORLD_9"
        WORLDS_2="$WORLD_10"
        ;;
    "$HOST_VPS6")
        VPS_NAME="VPS 6"
        WORLDS_1="$WORLD_11"
        WORLDS_2="$WORLD_12"
        ;;
    "$HOST_VPS7")
        VPS_NAME="VPS 7"
        WORLDS_1="$WORLD_13"
        WORLDS_2="$WORLD_14"
        ;;
    "$HOST_VPS8")
        VPS_NAME="VPS 8"
        WORLDS_1="$WORLD_15"
        WORLDS_2="$WORLD_16"
        ;;
    "$HOST_VPS9")
        VPS_NAME="VPS 9"
        WORLDS_1="$WORLD_17"
        WORLDS_2="$WORLD_18"
        ;;
    *)
        echo "ERROR: Unknown hostname: $HOST"
        echo
        echo "Configured hostnames:"
        echo "  VPS 1: $HOST_VPS1"
        echo "  VPS 2: $HOST_VPS2"
        echo "  VPS 3: $HOST_VPS3"
        echo "  VPS 4: $HOST_VPS4"
        echo "  VPS 5: $HOST_VPS5"
        echo "  VPS 6: $HOST_VPS6"
        echo "  VPS 7: $HOST_VPS7"
        echo "  VPS 8: $HOST_VPS8"
        echo "  VPS 9: $HOST_VPS9"
        exit 1
        ;;
esac

# ---------- Create directory ----------
mkdir -p "$NATON_DIR"

# ---------- Create one config ----------
create_config() {
    local file="$1"
    local worlds="$2"

    if [[ -f "$file" ]]; then
        cp -a "$file" "${file}.backup.$(date +%Y%m%d-%H%M%S)"
        echo "Backup created for $file"
    fi

    cat > "$file" <<EOF
#Naton Shopper Settings
#Generated by Naton automatic VPS setup

AcceptAidConfig={"configureAcceptAid"\:false,"disableAcceptAid"\:false}
AutoBondConfig={"price"\:{"gpToAdd"\:0,"staticPrice"\:0,"percentToAdd"\:0.0,"osbuddy"\:false,"runelite"\:false,"useStaticPrice"\:false,"runelitePriceType"\:"AVERAGE","arrowKeyAdjustment"\:2,"useArrowkeyPrice"\:true,"relistPolicy"\:{"nextPrice"\:{"gpToAdd"\:0,"staticPrice"\:0,"percentToAdd"\:0.0,"osbuddy"\:false,"runelite"\:false,"useStaticPrice"\:false,"runelitePriceType"\:"AVERAGE","arrowKeyAdjustment"\:3,"useArrowkeyPrice"\:true,"relistPolicy"\:{"nextPrice"\:{"gpToAdd"\:0,"staticPrice"\:0,"percentToAdd"\:0.0,"osbuddy"\:false,"runelite"\:false,"useStaticPrice"\:false,"runelitePriceType"\:"AVERAGE","arrowKeyAdjustment"\:4,"useArrowkeyPrice"\:true},"timeUnit"\:"MINUTES","range"\:{"max"\:10,"min"\:5,"lowerPlayerRandomization"\:-20.0,"type"\:"UNIFORM","upperPlayerRandomization"\:20.0}}},"timeUnit"\:"MINUTES","range"\:{"max"\:10,"min"\:5,"lowerPlayerRandomization"\:-20.0,"type"\:"UNIFORM","upperPlayerRandomization"\:20.0}}},"rebondDays"\:2,"cancelPendingBuyOffersForGold"\:false,"use"\:true,"obtainGoldFromMuleIfOut"\:false}
BankScrollConfig={"scrollMethod"\:"DEFAULT"}
CameraAngleConfig={"cameraAngleMin"\:70,"cameraAngleMax"\:100,"keepCameraAngleInRange"\:false}
CameraRotationConfig={"keepCameraRotationInRange"\:false,"cameraRotationMin"\:360,"cameraRotationMax"\:100}
CameraZoomConfig={"frequency"\:{"max"\:40,"min"\:15,"type"\:"UNIFORM"},"zoom"\:{"max"\:80,"avg"\:70,"min"\:50,"sd"\:8,"type"\:"NORMAL"},"enabled"\:false,"frequencyTimeUnit"\:"MINUTES"}
ChatHandlerConfig={"keyOptions"\:true,"loopSleep"\:{"max"\:125,"min"\:100,"lowerPlayerRandomization"\:-20.0,"type"\:"UNIFORM","upperPlayerRandomization"\:20.0},"keyContinue"\:true,"holdSpace"\:false,"beforeOption"\:{"max"\:5000,"avg"\:550,"min"\:180,"sd"\:192,"lowerPlayerRandomization"\:-20.0,"type"\:"NORMAL","upperPlayerRandomization"\:20.0},"beforeContinue"\:{"max"\:5000,"avg"\:420,"min"\:100,"sd"\:182,"lowerPlayerRandomization"\:-20.0,"type"\:"NORMAL","upperPlayerRandomization"\:20.0}}
ChatModeConfig={"clanChatMode"\:"ON","configureTradeChat"\:false,"tradeChatMode"\:"ON","configureGameChat"\:false,"publicChatMode"\:"ON","privateChatMode"\:"ALL","configureChannelChat"\:false,"channelChatMode"\:"ON","configureClanChat"\:false,"gameChatMode"\:"ALL","configurePrivateChat"\:false,"configurePublicChat"\:false}
DaxWalkerConfig={"enableSeed"\:false,"enableTeleporting"\:true,"useDentistWalker"\:false}
DiscordWebhookConfig={"sendOnFrequencyMinutes"\:60,"useWebooks"\:false,"sendOnDeath"\:false,"sendOnStart"\:false,"sendOnEnd"\:false,"sendOnInaccessible"\:false,"webhookUrl"\:"","sendOnLevel"\:false,"sendOnAntiPk"\:false,"sendOnFrequency"\:false}
DiscordWebhookOnAntiPkMessageConfig={"includeImage"\:true,"customMessage"\:"Anti-PK triggered in world \${world} at \${position}\!"}
DiscordWebhookOnDeathMessageConfig={"includeImage"\:true,"customMessage"\:"\${username} has died\!"}
DiscordWebhookOnEndMessageConfig={"includeImage"\:true,"customMessage"\:"Script Ending \${script-name}\\nRuntime\: \${script-runtime}\\nStop Reason\: \${stop-reason}"}
DiscordWebhookOnFrequencyMessageConfig={"includeImage"\:true,"customMessage"\:"Script Running \${script-name}\\nRuntime\: \${script-runtime}"}
DiscordWebhookOnInaccessibleMessageConfig={"includeImage"\:true,"customMessage"\:"Account Inaccessible\: \${username} is \${inaccessible-type}"}
DiscordWebhookOnLevelMessageConfig={"includeImage"\:true,"customMessage"\:"\${username} has leveled \${gained-skill-type} to \${gained-skill-level}"}
DiscordWebhookOnStartMessageConfig={"includeImage"\:true,"customMessage"\:"Script Starting \${script-name}"}
DynamicAntibanConfig={"alwaysHover"\:false,"timedActions"\:["CHECK_EXP","RANDOM_RIGHT_CLICK","MOVE_MOUSE","ROTATE_CAMERA","PICK_UP_MOUSE","MOUSE_LEAVE_GAME","EXAMINE_ENTITY","CHECK_TABS"],"reactionTimeScale"\:20.0,"useReactionTimes"\:false}
DynamicClientStateConfig={"openOnEnd"\:false,"hideOnStart"\:false}
DynamicControlsConfig={"mouseSpeedMin"\:100,"mouseSpeedMax"\:100,"cameraType"\:"CLIENT_CAMERA_ANTIBAN","customMouseSpeed"\:false}
DynamicOptionalFailsafeConfig={"adjustCameraZoom"\:false,"removeRoofs"\:false}
DynamicPrefZoomConfig={"usePrefZoom"\:false,"maxPrefZoom"\:50,"minPrefZoom"\:50}
DynamicSoundMuteConfig={"disableSoundsInGame"\:false,"disableSoundsLoginScreen"\:false}
DynamicStuckFailsafeConfig={"enabled"\:true}
DynamicTimeBasedHoppingConfig={"min"\:0,"max"\:0,"timeBasedHopping"\:false,"sd"\:0,"average"\:0}
DynamicWorldHopPlayersConfig={"maxPlayersInRange"\:0,"hopPlayerTalks"\:false,"onlyHopAtWorkArea"\:true,"playerSearchRange"\:0,"hopPlayersInRange"\:false}
DynamicWorldListConfig={"worlds"\:[$worlds],"excludeListedWorlds"\:false,"hopSequential"\:true,"hopRandom"\:false,"minSecondsPerWorld"\:0}
FkeyConfig={"useFkeys"\:false,"overrideFkeySetting"\:false}
LogoutOnEndConfig={"logoutOnEnd"\:false}
LogoutThumbsUpConfig={"thumbsUpChance"\:50,"enableClickingThumbsOnLogout"\:false,"onlyClickIfXHoursSince"\:false,"xHoursSince"\:6,"thumbsDownChance"\:50}
LoopSleepConfig={"overrideLoopSleep"\:false,"loopSleepRange"\:{"max"\:65,"min"\:45,"lowerPlayerRandomization"\:-20.0,"type"\:"UNIFORM","upperPlayerRandomization"\:20.0}}
MaxExchangeActionLengthConfig={"timeUnit"\:"MINUTES","range"\:{"max"\:90,"min"\:60,"lowerPlayerRandomization"\:-20.0,"type"\:"UNIFORM","upperPlayerRandomization"\:20.0}}
ResizableConfig={"resizableType"\:"RESIZABLE_MODERN","configureResizable"\:false}
ScreenshotOnEndConfig={"onlyAfterXMinutes"\:false,"screenshot"\:false,"xMinutes"\:60}
SleepModifierConfig={"modifier"\:{"max"\:105,"min"\:95,"type"\:"UNIFORM"},"enable"\:false}
buyBatch=BATCHES_OF_5
cashIn=false
cashInAmount=0
customBuyPrices={}
customSellPrices={}
defaultBuyPrice={"gpToAdd"\:0,"staticPrice"\:0,"percentToAdd"\:0.0,"osbuddy"\:false,"runelite"\:false,"useStaticPrice"\:false,"runelitePriceType"\:"AVERAGE","arrowKeyAdjustment"\:2,"useArrowkeyPrice"\:true}
defaultSellPrice={"gpToAdd"\:0,"staticPrice"\:0,"percentToAdd"\:0.0,"osbuddy"\:false,"runelite"\:false,"useStaticPrice"\:false,"runelitePriceType"\:"AVERAGE","arrowKeyAdjustment"\:-2,"useArrowkeyPrice"\:true}
enableGERestocking=true
equipBankTeleport=false
equipShopTeleport=false
fastOpenPacks=false
hopWhenEmpty=true
items=[{"itemId"\:6571,"quantity"\:0,"shopStockLimit"\:1,"transactionType"\:"BUY"},{"itemId"\:449,"quantity"\:4500,"shopStockLimit"\:4,"transactionType"\:"SELL"},{"itemId"\:442,"quantity"\:13000,"shopStockLimit"\:10,"transactionType"\:"SELL"},{"itemId"\:447,"quantity"\:13000,"shopStockLimit"\:10,"transactionType"\:"SELL"},{"itemId"\:444,"quantity"\:13000,"shopStockLimit"\:10,"transactionType"\:"SELL"}]
mule=false
muleAddress=127.0.0.1
muleForCoinsOnRestock=false
muleGPToKeep=500000
muleGoldTargetOnRestock=0
muleID=1
muleIfOver=1000000
muleThreshold=false
muleTripOnThreshold=true
napiMiniBreak={"breakLengthRange"\:{"max"\:280,"avg"\:242,"min"\:162,"sd"\:60,"lowerPlayerRandomization"\:-20.0,"type"\:"NORMAL","upperPlayerRandomization"\:20.0},"miniBreaking"\:false,"breakFrequencyRange"\:{"max"\:2145,"avg"\:1841,"min"\:473,"sd"\:368,"lowerPlayerRandomization"\:-20.0,"type"\:"NORMAL","upperPlayerRandomization"\:20.0}}
napiRandomAfk={"frequencyRange"\:{"max"\:2759,"avg"\:2126,"min"\:509,"sd"\:425,"lowerPlayerRandomization"\:-20.0,"type"\:"NORMAL","upperPlayerRandomization"\:20.0},"afkLengthRange"\:{"max"\:327,"avg"\:70,"min"\:36,"sd"\:17,"lowerPlayerRandomization"\:-20.0,"type"\:"NORMAL","upperPlayerRandomization"\:20.0},"mouseOffScreenChance"\:"ALWAYS","randomAfking"\:false}
progressionEntries=[]
repeatProgression=false
repeatWhenDone=false
restockOnStart=true
selectedShopTile={"y"\:5148,"z"\:0,"x"\:2465}
settingsVersion=0
shopNpcName=TzHaar-Hur-Lek
stopConditionExp={"allMatch"\:false,"conditions"\:[]}
useProgressiveMode=false
EOF

    chmod 644 "$file"
}

# ---------- Write configs ----------
create_config "$NATON_DIR/1.ini" "$WORLDS_1"
create_config "$NATON_DIR/2.ini" "$WORLDS_2"

echo
echo "=========================================="
echo " Naton setup completed"
echo " Host: $HOST"
echo " VPS:  $VPS_NAME"
echo "=========================================="
echo
echo "1.ini:"
grep '^DynamicWorldListConfig=' "$NATON_DIR/1.ini"
echo
echo "2.ini:"
grep '^DynamicWorldListConfig=' "$NATON_DIR/2.ini"
echo
echo "Files:"
ls -lh "$NATON_DIR/1.ini" "$NATON_DIR/2.ini"
