#!/bin/bash
set -euo pipefail

# ============================================================
# Naton Shopper - automatic setup for 4 VPS / 2 configs
#
# VPS 1: sgur.c.dedikuoti.lt  -> world lists 1 + 2
# VPS 2: rvsa.c.dedikuoti.lt  -> world lists 3 + 4
# VPS 3: t39e.c.dedikuoti.lt  -> world lists 5 + 6
# VPS 4: t4a4.c.dedikuoti.lt  -> world lists 7 + 8
#
# The same script is used on every VPS.
# ============================================================

NATON_DIR="/root/.onlybot/naton-scripts/Naton Shopper/settings"

HOST="$(hostname -f 2>/dev/null || hostname)"

# ---------- World lists ----------
WORLD_1='302,303,304,306,307,309,310,311,312,313,315,317,320,323,324,325,327,328,331'
WORLD_2='332,333,334,336,338,339,340,341,342,343,344,347,348,350,351,352,355,356'
WORLD_3='357,358,359,360,365,367,368,371,374,375,376,378,395,405,406,407,408,409'
WORLD_4='410,411,421,422,438,439,440,441,442,443,444,445,446,457,458,459,461,462'
WORLD_5='463,464,465,466,500,501,503,504,505,506,507,508,509,510,511,512,513,514'
WORLD_6='515,516,517,518,519,520,521,522,523,524,525,538,541,542,543,544,545,546'
WORLD_7='547,550,551,556,557,559,562,563,564,566,567,582,599,600,601,602,603,604'
WORLD_8='609,619,620,621,622,624,625,626,661,662,663,664,668,693,694,695,699,700'

# ---------- Select lists from hostname ----------
case "$HOST" in
    sgur.c.dedikuoti.lt)
        VPS_NAME="VPS 1"
        WORLDS_1="$WORLD_1"
        WORLDS_2="$WORLD_2"
        ;;
    rvsa.c.dedikuoti.lt)
        VPS_NAME="VPS 2"
        WORLDS_1="$WORLD_3"
        WORLDS_2="$WORLD_4"
        ;;
    t39e.c.dedikuoti.lt)
        VPS_NAME="VPS 3"
        WORLDS_1="$WORLD_5"
        WORLDS_2="$WORLD_6"
        ;;
    t4a4.c.dedikuoti.lt)
        VPS_NAME="VPS 4"
        WORLDS_1="$WORLD_7"
        WORLDS_2="$WORLD_8"
        ;;
    *)
        echo "ERROR: Unknown hostname: $HOST"
        echo "Allowed hostnames:"
        echo "  sgur.c.dedikuoti.lt"
        echo "  rvsa.c.dedikuoti.lt"
        echo "  t39e.c.dedikuoti.lt"
        echo "  t4a4.c.dedikuoti.lt"
        exit 1
        ;;
esac

# ---------- Create directory ----------
mkdir -p "$NATON_DIR"

# ---------- Create one config ----------
create_config() {
    local file="$1"
    local worlds="$2"

    if [[ -f "$file" ]]; then
        cp -a "$file" "${file}.backup.$(date +%Y%m%d-%H%M%S)"
        echo "Backup created for $file"
    fi

    cat > "$file" <<EOF
#Naton Shopper Settings
#Generated by Naton automatic VPS setup

AcceptAidConfig={"configureAcceptAid"\:false,"disableAcceptAid"\:false}
AutoBondConfig={"price"\:{"gpToAdd"\:0,"staticPrice"\:0,"percentToAdd"\:0.0,"osbuddy"\:false,"runelite"\:false,"useStaticPrice"\:false,"runelitePriceType"\:"AVERAGE","arrowKeyAdjustment"\:2,"useArrowkeyPrice"\:true,"relistPolicy"\:{"nextPrice"\:{"gpToAdd"\:0,"staticPrice"\:0,"percentToAdd"\:0.0,"osbuddy"\:false,"runelite"\:false,"useStaticPrice"\:false,"runelitePriceType"\:"AVERAGE","arrowKeyAdjustment"\:3,"useArrowkeyPrice"\:true,"relistPolicy"\:{"nextPrice"\:{"gpToAdd"\:0,"staticPrice"\:0,"percentToAdd"\:0.0,"osbuddy"\:false,"runelite"\:false,"useStaticPrice"\:false,"runelitePriceType"\:"AVERAGE","arrowKeyAdjustment"\:4,"useArrowkeyPrice"\:true},"timeUnit"\:"MINUTES","range"\:{"max"\:10,"min"\:5,"lowerPlayerRandomization"\:-20.0,"type"\:"UNIFORM","upperPlayerRandomization"\:20.0}}},"timeUnit"\:"MINUTES","range"\:{"max"\:10,"min"\:5,"lowerPlayerRandomization"\:-20.0,"type"\:"UNIFORM","upperPlayerRandomization"\:20.0}}},"rebondDays"\:2,"cancelPendingBuyOffersForGold"\:false,"use"\:true,"obtainGoldFromMuleIfOut"\:false}
BankScrollConfig={"scrollMethod"\:"DEFAULT"}
CameraAngleConfig={"cameraAngleMin"\:70,"cameraAngleMax"\:100,"keepCameraAngleInRange"\:false}
CameraRotationConfig={"keepCameraRotationInRange"\:false,"cameraRotationMin"\:360,"cameraRotationMax"\:100}
CameraZoomConfig={"frequency"\:{"max"\:40,"min"\:15,"type"\:"UNIFORM"},"zoom"\:{"max"\:80,"avg"\:70,"min"\:50,"sd"\:8,"type"\:"NORMAL"},"enabled"\:false,"frequencyTimeUnit"\:"MINUTES"}
ChatHandlerConfig={"keyOptions"\:true,"loopSleep"\:{"max"\:125,"min"\:100,"lowerPlayerRandomization"\:-20.0,"type"\:"UNIFORM","upperPlayerRandomization"\:20.0},"keyContinue"\:true,"holdSpace"\:false,"beforeOption"\:{"max"\:5000,"avg"\:550,"min"\:180,"sd"\:192,"lowerPlayerRandomization"\:-20.0,"type"\:"NORMAL","upperPlayerRandomization"\:20.0},"beforeContinue"\:{"max"\:5000,"avg"\:420,"min"\:100,"sd"\:182,"lowerPlayerRandomization"\:-20.0,"type"\:"NORMAL","upperPlayerRandomization"\:20.0}}
ChatModeConfig={"clanChatMode"\:"ON","configureTradeChat"\:false,"tradeChatMode"\:"ON","configureGameChat"\:false,"publicChatMode"\:"ON","privateChatMode"\:"ALL","configureChannelChat"\:false,"channelChatMode"\:"ON","configureClanChat"\:false,"gameChatMode"\:"ALL","configurePrivateChat"\:false,"configurePublicChat"\:false}
DaxWalkerConfig={"enableSeed"\:false,"enableTeleporting"\:true,"useDentistWalker"\:false}
DiscordWebhookConfig={"sendOnFrequencyMinutes"\:60,"useWebooks"\:false,"sendOnDeath"\:false,"sendOnStart"\:false,"sendOnEnd"\:false,"sendOnInaccessible"\:false,"webhookUrl"\:"","sendOnLevel"\:false,"sendOnAntiPk"\:false,"sendOnFrequency"\:false}
DiscordWebhookOnAntiPkMessageConfig={"includeImage"\:true,"customMessage"\:"Anti-PK triggered in world \${world} at \${position}\!"}
DiscordWebhookOnDeathMessageConfig={"includeImage"\:true,"customMessage"\:"\${username} has died\!"}
DiscordWebhookOnEndMessageConfig={"includeImage"\:true,"customMessage"\:"Script Ending \${script-name}\\nRuntime\: \${script-runtime}\\nStop Reason\: \${stop-reason}"}
DiscordWebhookOnFrequencyMessageConfig={"includeImage"\:true,"customMessage"\:"Script Running \${script-name}\\nRuntime\: \${script-runtime}"}
DiscordWebhookOnInaccessibleMessageConfig={"includeImage"\:true,"customMessage"\:"Account Inaccessible\: \${username} is \${inaccessible-type}"}
DiscordWebhookOnLevelMessageConfig={"includeImage"\:true,"customMessage"\:"\${username} has leveled \${gained-skill-type} to \${gained-skill-level}"}
DiscordWebhookOnStartMessageConfig={"includeImage"\:true,"customMessage"\:"Script Starting \${script-name}"}
DynamicAntibanConfig={"alwaysHover"\:false,"timedActions"\:["CHECK_EXP","RANDOM_RIGHT_CLICK","MOVE_MOUSE","ROTATE_CAMERA","PICK_UP_MOUSE","MOUSE_LEAVE_GAME","EXAMINE_ENTITY","CHECK_TABS"],"reactionTimeScale"\:20.0,"useReactionTimes"\:false}
DynamicClientStateConfig={"openOnEnd"\:false,"hideOnStart"\:false}
DynamicControlsConfig={"mouseSpeedMin"\:100,"mouseSpeedMax"\:100,"cameraType"\:"CLIENT_CAMERA_ANTIBAN","customMouseSpeed"\:false}
DynamicOptionalFailsafeConfig={"adjustCameraZoom"\:false,"removeRoofs"\:false}
DynamicPrefZoomConfig={"usePrefZoom"\:false,"maxPrefZoom"\:50,"minPrefZoom"\:50}
DynamicSoundMuteConfig={"disableSoundsInGame"\:false,"disableSoundsLoginScreen"\:false}
DynamicStuckFailsafeConfig={"enabled"\:true}
DynamicTimeBasedHoppingConfig={"min"\:0,"max"\:0,"timeBasedHopping"\:false,"sd"\:0,"average"\:0}
DynamicWorldHopPlayersConfig={"maxPlayersInRange"\:0,"hopPlayerTalks"\:false,"onlyHopAtWorkArea"\:true,"playerSearchRange"\:0,"hopPlayersInRange"\:false}
DynamicWorldListConfig={"excludeListedWorlds"\:false,"hopSequential"\:false,"worlds":[$worlds]}
FkeyConfig={"useFkeys"\:false,"overrideFkeySetting"\:false}
LogoutOnEndConfig={"logoutOnEnd"\:false}
LogoutThumbsUpConfig={"thumbsUpChance"\:50,"enableClickingThumbsOnLogout"\:false,"onlyClickIfXHoursSince"\:false,"xHoursSince"\:6,"thumbsDownChance"\:50}
LoopSleepConfig={"overrideLoopSleep"\:false,"loopSleepRange"\:{"max"\:65,"min"\:45,"lowerPlayerRandomization"\:-20.0,"type"\:"UNIFORM","upperPlayerRandomization"\:20.0}}
MaxExchangeActionLengthConfig={"timeUnit"\:"MINUTES","range"\:{"max"\:90,"min"\:60,"lowerPlayerRandomization"\:-20.0,"type"\:"UNIFORM","upperPlayerRandomization"\:20.0}}
ResizableConfig={"resizableType"\:"RESIZABLE_MODERN","configureResizable"\:false}
ScreenshotOnEndConfig={"onlyAfterXMinutes"\:false,"screenshot"\:false,"xMinutes"\:60}
SleepModifierConfig={"modifier"\:{"max"\:105,"min"\:95,"type"\:"UNIFORM"},"enable"\:false}
cashIn=false
cashInAmount=0
customBuyPrices={}
customSellPrices={}
defaultBuyPrice={"gpToAdd"\:0,"staticPrice"\:0,"percentToAdd"\:0.0,"osbuddy"\:false,"runelite"\:false,"useStaticPrice"\:false,"runelitePriceType"\:"AVERAGE","arrowKeyAdjustment"\:2,"useArrowkeyPrice"\:true}
defaultSellPrice={"gpToAdd"\:0,"staticPrice"\:0,"percentToAdd"\:0.0,"osbuddy"\:false,"runelite"\:false,"useStaticPrice"\:false,"runelitePriceType"\:"AVERAGE","arrowKeyAdjustment"\:-2,"useArrowkeyPrice"\:true}
enableGERestocking=true
equipBankTeleport=false
equipShopTeleport=false
fastOpenPacks=false
hopWhenEmpty=true
items=[{"itemId"\:6571,"quantity"\:0,"shopStockLimit"\:1,"transactionType"\:"BUY"},{"itemId"\:449,"quantity"\:4500,"shopStockLimit"\:4,"transactionType"\:"SELL"},{"itemId"\:442,"quantity"\:13000,"shopStockLimit"\:10,"transactionType"\:"SELL"},{"itemId"\:447,"quantity"\:13000,"shopStockLimit"\:10,"transactionType"\:"SELL"},{"itemId"\:444,"quantity"\:13000,"shopStockLimit"\:10,"transactionType"\:"SELL"}]
mule=false
muleAddress=127.0.0.1
muleForCoinsOnRestock=false
muleGPToKeep=500000
muleGoldTargetOnRestock=0
muleID=1
muleIfOver=1000000
muleThreshold=false
napiMiniBreak={"breakLengthRange"\:{"max"\:280,"avg"\:242,"min"\:162,"sd"\:60,"lowerPlayerRandomization"\:-20.0,"type"\:"NORMAL","upperPlayerRandomization"\:20.0},"miniBreaking"\:false,"breakFrequencyRange"\:{"max"\:2145,"avg"\:1841,"min"\:473,"sd"\:368,"lowerPlayerRandomization"\:-20.0,"type"\:"NORMAL","upperPlayerRandomization"\:20.0}}
napiRandomAfk={"frequencyRange"\:{"max"\:2759,"avg"\:2126,"min"\:509,"sd"\:425,"lowerPlayerRandomization"\:-20.0,"type"\:"NORMAL","upperPlayerRandomization"\:20.0},"afkLengthRange"\:{"max"\:327,"avg"\:70,"min"\:36,"sd"\:17,"lowerPlayerRandomization"\:-20.0,"type"\:"NORMAL","upperPlayerRandomization"\:20.0},"mouseOffScreenChance"\:"ALWAYS","randomAfking"\:false}
progressionEntries=[]
repeatProgression=false
repeatWhenDone=false
selectedShopTile={"y"\:5148,"z"\:0,"x"\:2465}
settingsVersion=0
shopNpcName=TzHaar-Hur-Lek
stopConditionExp={"allMatch"\:false,"conditions"\:[]}
useProgressiveMode=false
EOF

    chmod 644 "$file"
}

# ---------- Write configs ----------
create_config "$NATON_DIR/1.ini" "$WORLDS_1"
create_config "$NATON_DIR/2.ini" "$WORLDS_2"

echo
echo "=========================================="
echo " Naton setup completed"
echo " Host: $HOST"
echo " VPS:  $VPS_NAME"
echo "=========================================="
echo
echo "1.ini:"
grep '^DynamicWorldListConfig=' "$NATON_DIR/1.ini"
echo
echo "2.ini:"
grep '^DynamicWorldListConfig=' "$NATON_DIR/2.ini"
echo
echo "Files:"
ls -lh "$NATON_DIR/1.ini" "$NATON_DIR/2.ini"
