#!/bin/bash
set -euo pipefail

# Naton Shopper - automatic setup for 9 VPS / 2 configs each
# AutoBond enabled: rebondDays=2
# Worlds are distributed automatically across 18 configs.
# VPS 8: w8f0
# VPS 9: w8f1

NATON_DIR="/root/.onlybot/naton-scripts/Naton Shopper/settings"
HOST="$(hostname -s 2>/dev/null || hostname)"

# ---------- World lists (SEQUENTIAL ORDER) ----------
WORLDS_1="302,303,304,305,306,307,309,310,311,312,313,314,315"
WORLDS_2="317,320,321,322,323,324,325,327,328,329,330,331,332"
WORLDS_3="333,334,336,337,338,339,340,341,342,343,344,346"
WORLDS_4="347,348,350,351,352,354,355,356,357,358,359,360"
WORLDS_5="362,365,367,368,369,370,371,374,375,376,377,378"
WORLDS_6="385,386,387,388,389,390,394,395,402,403,404,405"
WORLDS_7="406,407,408,409,410,411,412,421,422,424,425,426"
WORLDS_8="438,439,440,441,442,443,444,445,446,457,458,459"
WORLDS_9="461,462,463,464,465,466,470,471,472,473,474,475"
WORLDS_10="476,477,478,479,480,481,482,484,485,486,487,488"
WORLDS_11="489,490,491,492,493,494,495,496,500,501,503,504"
WORLDS_12="505,506,507,508,509,510,511,512,513,514,515,516"
WORLDS_13="517,518,519,520,521,522,523,524,525,531,532,533"
WORLDS_14="534,535,536,538,541,542,543,544,545,546,547,550"
WORLDS_15="551,556,557,559,562,563,564,566,567,569,573,574"
WORLDS_16="575,582,590,591,596,597,599,600,601,602,603,604"
WORLDS_17="609,610,611,612,613,614,615,619,620,621,622,624"
WORLDS_18="625,626,661,662,663,664,668,693,694,695,699,700"

# ---------- Select lists from hostname ----------
case "$HOST" in
    ui0z)
        VPS_NAME="VPS 1"
        WORLDS_1="${WORLDS_1}"
        WORLDS_2="${WORLDS_2}"
        ;;
    sbk2)
        VPS_NAME="VPS 2"
        WORLDS_1="${WORLDS_3}"
        WORLDS_2="${WORLDS_4}"
        ;;
    uzmq)
        VPS_NAME="VPS 3"
        WORLDS_1="${WORLDS_5}"
        WORLDS_2="${WORLDS_6}"
        ;;
    ue4v)
        VPS_NAME="VPS 4"
        WORLDS_1="${WORLDS_7}"
        WORLDS_2="${WORLDS_8}"
        ;;
    uehp)
        VPS_NAME="VPS 5"
        WORLDS_1="${WORLDS_9}"
        WORLDS_2="${WORLDS_10}"
        ;;
    uq6q)
        VPS_NAME="VPS 6"
        WORLDS_1="${WORLDS_11}"
        WORLDS_2="${WORLDS_12}"
        ;;
    tl70)
        VPS_NAME="VPS 7"
        WORLDS_1="${WORLDS_13}"
        WORLDS_2="${WORLDS_14}"
        ;;
    w8f0)
        VPS_NAME="VPS 8"
        WORLDS_1="${WORLDS_15}"
        WORLDS_2="${WORLDS_16}"
        ;;
    w8f1)
        VPS_NAME="VPS 9"
        WORLDS_1="${WORLDS_17}"
        WORLDS_2="${WORLDS_18}"
        ;;
    *)
        echo "ERROR: Unknown hostname: $HOST"
        echo "Allowed: ui0z sbk2 uzmq ue4v uehp uq6q tl70 w8f0 w8f1"
        exit 1
        ;;
esac

mkdir -p "$NATON_DIR"

create_config() {
    local file="$1"
    local worlds="$2"

    if [[ -f "$file" ]]; then
        cp -a "$file" "${file}.backup.$(date +%Y%m%d-%H%M%S)"
        echo "Backup created for $file"
    fi

    cat > "$file" <<EOF
#Naton Shopper Settings
#Generated by 9-VPS automatic setup
AcceptAidConfig={"configureAcceptAid"\:false,"disableAcceptAid"\:false}
AutoBondConfig={"dontSellItemsForGold"\:false,"obtainGoldFromMuleIfOut"\:false,"use"\:true,"rebondDays"\:2,"price"\:{"percentToAdd"\:0.0,"gpToAdd"\:0,"runelite"\:false,"useStaticPrice"\:false,"relistPolicy"\:{"range"\:{"min"\:5,"max"\:10,"type"\:"UNIFORM","upperPlayerRandomization"\:20.0,"lowerPlayerRandomization"\:-20.0},"nextPrice"\:{"percentToAdd"\:0.0,"gpToAdd"\:0,"runelite"\:false,"useStaticPrice"\:false,"relistPolicy"\:{"range"\:{"min"\:5,"max"\:10,"type"\:"UNIFORM","upperPlayerRandomization"\:20.0,"lowerPlayerRandomization"\:-20.0},"nextPrice"\:{"percentToAdd"\:0.0,"gpToAdd"\:0,"runelite"\:false,"useStaticPrice"\:false,"useArrowkeyPrice"\:true,"staticPrice"\:0,"arrowKeyAdjustment"\:4,"runelitePriceType"\:"AVERAGE","osbuddy"\:false},"timeUnit"\:"MINUTES"},"useArrowkeyPrice"\:true,"staticPrice"\:0,"arrowKeyAdjustment"\:3,"runelitePriceType"\:"AVERAGE","osbuddy"\:false},"timeUnit"\:"MINUTES"},"useArrowkeyPrice"\:true,"staticPrice"\:0,"arrowKeyAdjustment"\:2,"runelitePriceType"\:"AVERAGE","osbuddy"\:false},"cancelPendingBuyOffersForGold"\:false}
BankScrollConfig={"scrollMethod"\:"DEFAULT"}
CameraAngleConfig={"cameraAngleMin"\:70,"cameraAngleMax"\:100,"keepCameraAngleInRange"\:false}
CameraRotationConfig={"keepCameraRotationInRange"\:false,"cameraRotationMin"\:360,"cameraRotationMax"\:100}
CameraZoomConfig={"zoom"\:{"min"\:50,"max"\:80,"sd"\:8,"avg"\:70,"type"\:"NORMAL"},"frequencyTimeUnit"\:"MINUTES","frequency"\:{"min"\:15,"max"\:40,"type"\:"UNIFORM"},"enabled"\:false}
ChatHandlerConfig={"loopSleep"\:{"min"\:100,"max"\:125,"type"\:"UNIFORM","upperPlayerRandomization"\:20.0,"lowerPlayerRandomization"\:-20.0},"keyOptions"\:true,"beforeContinue"\:{"min"\:100,"max"\:5000,"sd"\:182,"avg"\:420,"type"\:"NORMAL","upperPlayerRandomization"\:20.0,"lowerPlayerRandomization"\:-20.0},"keyContinue"\:true,"beforeOption"\:{"min"\:180,"max"\:5000,"sd"\:192,"avg"\:550,"type"\:"NORMAL","upperPlayerRandomization"\:20.0,"lowerPlayerRandomization"\:-20.0},"holdSpace"\:false}
ChatModeConfig={"gameChatMode"\:"ALL","channelChatMode"\:"ON","configurePrivateChat"\:false,"configureTradeChat"\:false,"publicChatMode"\:"ON","configureClanChat"\:false,"privateChatMode"\:"ALL","tradeChatMode"\:"ON","configurePublicChat"\:false,"configureGameChat"\:false,"clanChatMode"\:"ON"}
DaxWalkerConfig={"enableTeleporting"\:true,"enableSeed"\:false,"useDentistWalker"\:true}
DiscordWebhookConfig={"sendOnDeath"\:false,"sendOnFrequencyMinutes"\:60,"useWebooks"\:false,"sendOnInaccessible"\:false,"sendOnStart"\:false,"sendOnPet"\:false,"sendOnEnd"\:false,"itemGainedWatchList"\:"","webhookUrl"\:"","sendOnItemGained"\:false,"sendOnAntiPk"\:false,"sendOnFrequency"\:false,"itemGainedMinValue"\:0,"sendOnLevel"\:false}
DiscordWebhookOnAntiPkMessageConfig={"customMessage"\:"Anti-PK triggered in world \${world} at \${position}\!","includeImage"\:true}
DiscordWebhookOnDeathMessageConfig={"customMessage"\:"\${username} has died\!","includeImage"\:true}
DiscordWebhookOnEndMessageConfig={"customMessage"\:"Script Ending \${script-name}\\nRuntime\: \${script-runtime}\\nStop Reason\: \${stop-reason}","includeImage"\:true}
DiscordWebhookOnFrequencyMessageConfig={"customMessage"\:"Script Running \${script-name}\\nRuntime\: \${script-runtime}","includeImage"\:true}
DiscordWebhookOnInaccessibleMessageConfig={"customMessage"\:"Account Inaccessible\: \${username} is \${inaccessible-type}","includeImage"\:true}
DiscordWebhookOnItemGainedMessageConfig={"customMessage"\:"\${username} received \${gained-item-quantity} x \${gained-item-name} (worth \${gained-item-value} gp)\!","includeImage"\:true}
DiscordWebhookOnLevelMessageConfig={"customMessage"\:"\${username} has leveled \${gained-skill-type} to \${gained-skill-level}","includeImage"\:true}
DiscordWebhookOnPetMessageConfig={"customMessage"\:"Pet alert for \${username}\! \${pet-message}","includeImage"\:true}
DiscordWebhookOnStartMessageConfig={"customMessage"\:"Script Starting \${script-name}","includeImage"\:true}
DynamicAntibanConfig={"alwaysHover"\:false,"timedActions"\:["CHECK_EXP","RANDOM_RIGHT_CLICK","MOVE_MOUSE","ROTATE_CAMERA","PICK_UP_MOUSE","MOUSE_LEAVE_GAME","EXAMINE_ENTITY","CHECK_TABS"],"reactionTimeScale"\:20.0,"useReactionTimes"\:false}
DynamicClientStateConfig={"openOnEnd"\:false,"hideOnStart"\:false}
DynamicControlsConfig={"customMouseSpeed"\:false,"mouseSpeedMax"\:100,"cameraType"\:"CLIENT_CAMERA_ANTIBAN","mouseSpeedMin"\:100}
DynamicOptionalFailsafeConfig={"removeRoofs"\:false,"adjustCameraZoom"\:false}
DynamicPrefZoomConfig={"maxPrefZoom"\:50,"usePrefZoom"\:false,"minPrefZoom"\:50}
DynamicSoundMuteConfig={"disableSoundsLoginScreen"\:false,"disableSoundsInGame"\:false}
DynamicStuckFailsafeConfig={"enabled"\:true}
DynamicTimeBasedHoppingConfig={"average"\:0,"timeBasedHopping"\:false,"min"\:0,"sd"\:0,"max"\:0}
DynamicWorldHopPlayersConfig={"hopPlayerTalks"\:false,"onlyHopAtWorkArea"\:true,"hopPlayersInRange"\:false,"maxPlayersInRange"\:0,"playerSearchRange"\:0}
DynamicWorldListConfig={"worlds"\:[$worlds],"excludeListedWorlds"\:false,"hopSequential"\:true,"hopRandom"\:false,"minSecondsPerWorld"\:0}
FkeyConfig={"useFkeys"\:false,"overrideFkeySetting"\:false}
LogoutOnEndConfig={"logoutOnEnd"\:false}
LogoutThumbsUpConfig={"xHoursSince"\:6,"enableClickingThumbsOnLogout"\:false,"onlyClickIfXHoursSince"\:false,"thumbsUpChance"\:50,"thumbsDownChance"\:50}
LoopSleepConfig={"loopSleepRange"\:{"min"\:45,"max"\:65,"type"\:"UNIFORM","upperPlayerRandomization"\:20.0,"lowerPlayerRandomization"\:-20.0},"overrideLoopSleep"\:false}
MaxExchangeActionLengthConfig={"range"\:{"min"\:60,"max"\:90,"type"\:"UNIFORM","upperPlayerRandomization"\:20.0,"lowerPlayerRandomization"\:-20.0},"timeUnit"\:"MINUTES"}
ResizableConfig={"configureResizable"\:false,"resizableType"\:"RESIZABLE_MODERN"}
ScreenshotOnEndConfig={"screenshot"\:false,"onlyAfterXMinutes"\:false,"xMinutes"\:60}
SleepModifierConfig={"modifier"\:{"min"\:95,"max"\:105,"type"\:"UNIFORM"},"enable"\:false}
buyBatch=BATCHES_OF_5
cashIn=false
cashInAmount=0
customBuyPrices={}
customSellPrices={}
defaultBuyPrice={"percentToAdd"\:0.0,"gpToAdd"\:0,"runelite"\:false,"useStaticPrice"\:false,"useArrowkeyPrice"\:true,"staticPrice"\:0,"arrowKeyAdjustment"\:2,"runelitePriceType"\:"AVERAGE","osbuddy"\:false}
defaultSellPrice={"percentToAdd"\:0.0,"gpToAdd"\:0,"runelite"\:false,"useStaticPrice"\:false,"useArrowkeyPrice"\:true,"staticPrice"\:0,"arrowKeyAdjustment"\:-2,"runelitePriceType"\:"AVERAGE","osbuddy"\:false}
enableGERestocking=true
equipBankTeleport=false
equipShopTeleport=false
fastOpenPacks=false
hopWhenEmpty=true
items=[{"itemId"\:6571,"transactionType"\:"BUY","shopStockLimit"\:1,"quantity"\:0},{"itemId"\:449,"transactionType"\:"SELL","shopStockLimit"\:6,"quantity"\:4500},{"itemId"\:444,"transactionType"\:"SELL","shopStockLimit"\:22,"quantity"\:13000},{"itemId"\:447,"transactionType"\:"SELL","shopStockLimit"\:14,"quantity"\:13000},{"itemId"\:442,"transactionType"\:"SELL","shopStockLimit"\:22,"quantity"\:13000}]
mule=false
muleAddress=127.0.0.1
muleForCoinsOnRestock=false
muleGPToKeep=500000
muleGoldTargetOnRestock=0
muleID=1
muleIfOver=1000000
muleThreshold=false
muleTripOnThreshold=true
napiMiniBreak={"breakLengthRange"\:{"min"\:80,"max"\:433,"sd"\:27,"avg"\:108,"type"\:"NORMAL","upperPlayerRandomization"\:20.0,"lowerPlayerRandomization"\:-20.0},"breakFrequencyRange"\:{"min"\:636,"max"\:2045,"sd"\:288,"avg"\:1442,"type"\:"NORMAL","upperPlayerRandomization"\:20.0,"lowerPlayerRandomization"\:-20.0},"miniBreaking"\:false}
napiRandomAfk={"frequencyRange"\:{"min"\:590,"max"\:3012,"sd"\:138,"avg"\:692,"type"\:"NORMAL","upperPlayerRandomization"\:20.0,"lowerPlayerRandomization"\:-20.0},"afkLengthRange"\:{"min"\:56,"max"\:404,"sd"\:76,"avg"\:306,"type"\:"NORMAL","upperPlayerRandomization"\:20.0,"lowerPlayerRandomization"\:-20.0},"mouseOffScreenChance"\:"ALWAYS","randomAfking"\:false}
progressionEntries=[]
repeatProgression=false
repeatWhenDone=false
restockOnStart=true
selectedShopTile={"x"\:2524,"y"\:5075,"z"\:0}
settingsVersion=0
shopNpcName=TzHaar-Hur-Rin
stopConditionExp={"allMatch"\:false,"conditions"\:[]}
useProgressiveMode=false
EOF

    chmod 644 "$file"
}

create_config "$NATON_DIR/1.ini" "$WORLDS_1"
create_config "$NATON_DIR/2.ini" "$WORLDS_2"

echo "=========================================="
echo " Naton setup completed"
echo " Host: $HOST"
echo " VPS:  $VPS_NAME"
echo "=========================================="

echo "1.ini:"
grep '^DynamicWorldListConfig=' "$NATON_DIR/1.ini"

echo "2.ini:"
grep '^DynamicWorldListConfig=' "$NATON_DIR/2.ini"

echo "Files:"
ls -lh "$NATON_DIR/1.ini" "$NATON_DIR/2.ini"
